# permissions for end users to edit sparks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: spark-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: spark-helm-operator
    app.kubernetes.io/part-of: spark-helm-operator
    app.kubernetes.io/managed-by: kustomize
  name: spark-editor-role
rules:
- apiGroups:
  - apachespark.apache.org
  resources:
  - sparks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apachespark.apache.org
  resources:
  - sparks/status
  verbs:
  - get
