# permissions for end users to view sparks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: spark-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: spark-helm-operator
    app.kubernetes.io/part-of: spark-helm-operator
    app.kubernetes.io/managed-by: kustomize
  name: spark-viewer-role
rules:
- apiGroups:
  - apachespark.my.domain
  resources:
  - sparks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apachespark.my.domain
  resources:
  - sparks/status
  verbs:
  - get
