# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/apachespark.apache.org_sparks.yaml
- bases/sparkoperator.k8s.io_sparkapplications.yaml
- bases/sparkoperator.k8s.io_scheduledsparkapplications.yaml
#+kubebuilder:scaffold:crdkustomizeresource
